#!/bin/sh

#Adds the IPv4 address to the lighttpd conf

#Exit on errors
set -e

# Get interface to use from arg 1, or default wlan0
IPv4_IFACE=${1:-wlan0}

echo "var.bind_addr = \""$(ip -o -4 a show $IPv4_IFACE | grep -Eo 'inet\s[^/]+' | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')\"
